pipeline {
    agent any

    tools {
        maven 'maven 3.9.12'
    }

    stages {
        stage("build") {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage("test") {
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running tests'
                dir('worker') {
                    sh 'mvn test'
                }
            }
        }
        stage("package") {
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            echo 'Building multibranch pipeline for worker is completed.'
        }
        failure {
            slackSend (channel: "#ci-cd", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
        success {
            slackSend (channel: "#ci-cd", message: "Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
    }
}
