pipeline {
    agent {
        docker {
            image 'maven:3-sapmachine-21'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage("build") {
            steps {
                echo 'Building worker app'
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage("test") {
            steps {
                echo 'Running tests'
                dir('worker') {
                    sh 'mvn clean test'
                }
            }
        }
        stage("package") {
            steps {
                echo 'Packaging worker app into a jarfile'
                dir('worker') {
                    sh 'mvn package'
                    archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        always {
            echo 'Building multibranch pipeline for worker is completed.'
        }
        failure {
            slackSend (channel: "#ci-cd", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
        success {
            slackSend (channel: "#ci-cd", message: "Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
    }
}
