pipeline {
    agent any
    environment {
        DOCKER_HUB_USER = credentials('docker-hub-login')
    }
    stages {
        stage("build") {
            when {
                anyOf {
                    changeRequest()
                    changeset "**/worker/**"
                }
            }
            agent {
                docker {
                    image "maven:3-sapmachine-21"
                    args "-v $HOME/.m2:/root/.m2"
                }
            }
            steps {
                echo "Building worker app"
                dir("worker") {
                    sh "mvn compile"
                }
            }
        }
        stage("test") {
            when {
                anyOf {
                    changeRequest()
                    changeset "**/worker/**"
                }
            }
            agent {
                docker {
                    image "maven:3-sapmachine-21"
                    args "-v $HOME/.m2:/root/.m2"
                }
            }
            steps {
                echo "Running tests"
                dir("worker") {
                    sh "mvn clean test"
                }
            }
        }
        stage("package") {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            agent {
                docker {
                    image "maven:3-sapmachine-21"
                    args "-v $HOME/.m2:/root/.m2"
                }
            }
            steps {
                echo "Packaging worker app into a jarfile"
                dir("worker") {
                    sh "mvn package"
                    archiveArtifacts artifacts: "**/target/*.jar", fingerprint: true
                }
            }
        }
        stage("docker-package") {
            agent any
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo "Packaging worker app with docker"
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'docker-hub-credentials') {
                        def image = docker.build("${DOCKER_HUB_USER}/worker:v${env.BUILD_ID}", "./worker")
                        image.push()
                        image.push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Building multibranch pipeline for worker is completed."
        }
        failure {
            slackSend (channel: "#ci-cd", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
        success {
            slackSend (channel: "#ci-cd", message: "Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER}")
        }
    }
}
